# Generated by Django 3.2.21 on 2023-09-07 16:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('photo', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Phto',
            new_name='Photo',
        ),
    ]
